# Generated by Django 5.2.4 on 2025-07-14 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('photo_url', models.URLField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('BENEFICIAIRE', 'Bénéficiaire'), ('ADMIN', 'Administrateur')], default='BENEFICIAIRE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenu_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_enfants', models.PositiveIntegerField()),
                ('statut_familial', models.CharField(choices=[('célibataire', 'Célibataire'), ('marié', 'Marié(e)'), ('veuf', 'Veuf/Veuve')], max_length=20)),
                ('fokontany', models.CharField(max_length=50)),
                ('conjoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.beneficiaire')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaire', to='users.utilisateur')),
            ],
        ),
    ]
